palette = "material"

[character]
error_symbol = "[ğŸŒ¶ï¸](bold #ff5555)"
success_symbol = "[ğŸŒ¶ï¸](bold #50fa7b)"

[username]
format = "[$user]($style) on "

[palettes.material]
black   = '#666666'
red     = '#eb606b'
green   = '#c3e88d'
yellow  = '#f7eb95'
blue    = '#80cbc4'
magenta = '#ff2f90'
cyan    = '#aeddff'
white   = '#ffffff'
